# Generated by Django 3.2.4 on 2021-08-19 01:17

import core.utils.crypto_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_signup_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.utils.crypto_utils.token_alphanum16, max_length=32)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('hp_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hpuser')),
            ],
        ),
    ]
