# Generated by Django 3.2.4 on 2021-08-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210819_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='pagename',
        ),
    ]
