# Generated by Django 3.2.4 on 2021-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_signup_pagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpuser',
            name='pagename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
