# Generated by Django 3.2.4 on 2021-11-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('hp_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hpuser')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.blocktemplate')),
            ],
        ),
    ]
