# Generated by Django 3.2.4 on 2021-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_block_blocktemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpuser',
            name='pagename',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
