# Generated by Django 3.2.4 on 2021-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_hpuser_pagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='data',
            new_name='block_data',
        ),
    ]
