# Generated by Django 3.2.4 on 2021-11-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_data_block_block_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_data',
            new_name='data',
        ),
    ]
