# Generated by Django 3.2.4 on 2021-11-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211108_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='pagename',
            field=models.CharField(max_length=128),
        ),
    ]
