# Generated by Django 3.2.4 on 2023-06-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220203_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tahash',
        ),
    ]
